### ISSUE TITLE
Intended to be compatible with logarithmic depth?

### ISSUE THREAD

**Issue by benferns** [Alchemist0823/three.quarks#28]
I get the following error in BatchedParticleRenderer materials when switching the threejs renderer to logarithmic depth:

`THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false
Program Info Log: Vertex shader is not compiled.
VERTEX
ERROR: 0:123: 'isPerspectiveMatrix' : no matching overloaded function found`

**Comment by Alchemist0823** [comment]
Thanks for pointing out and ur merge request. I was busy with other stuff. Now I  am back will merge your request.

**Comment by Alchemist0823** [comment]
#38
