### ISSUE TITLE
Ktx2 Gpu compressed format for particel textures

### ISSUE THREAD

**Issue by arpu** [Alchemist0823/three.quarks#31]
Hello

would it be possible to ad ktx2 for the particel textures?

**Comment by Alchemist0823** [comment]
Never hear of it. Will check it. What advantage does ktx2 provide?

**Comment by arpu** [comment]
ktx2 is gpu compressed texture format work on all plattforms ios android desktop

**Comment by Alchemist0823** [comment]
if browser supports it, this library supports it. the library load texture from url or uncompressed base64 image.

**Comment by Alchemist0823** [comment]
actually, https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_texture_ktx.html. as long as you load with KTXLoader you will be available to use it.
