### ISSUE TITLE
Max particles

### ISSUE THREAD

**Issue by marwie** [Alchemist0823/three.quarks#33]
Hello,

looks like ``maxParticle`` is outdated / not used yet or anymore in the examples? And it seems like the internal property is not used?

https://github.com/Alchemist0823/three.quarks/search?q=maxParticles

Would you recommend handling this manually using the emitters over distance and life?

**Comment by Alchemist0823** [comment]
because the new system uses autoScaling maxParticle

**Comment by marwie** [comment]
Yeah currently I clamp how many particles I emit to the max count but would be nice if that would be handled internally automatically (if a max count is set)

**Comment by Alchemist0823** [comment]
After some consideration, I feel max particles setting is not good design option. It feels like an artificial limit on the particle system.
