### ISSUE TITLE
Usage of ``ParticleSystem.emit``

### ISSUE THREAD

**Issue by marwie** [Alchemist0823/three.quarks#36]
Hello,

I have a case where I have a one-shot effect with a duration of 1 and not looping. I still want to be able to call ``emit`` on this effect and have the system emit the provided amount of particles that frame. Currently the internal ``emitEnded``  flag prevents that. 

What would you suggest on how to make this still work and force it to emit particles?

Here's a short video where I set ``emitEnded`` to false before calling ``emit`` in a 1 sec interval

https://user-images.githubusercontent.com/5083203/201334382-d6aa8eda-bd2b-498e-be14-cdf749e300a4.mp4  

the system is setup like this:
![image](https://user-images.githubusercontent.com/5083203/201334634-faaa9c6b-82ca-4a54-872e-f9d3a90e5ab1.png)

**Comment by Alchemist0823** [comment]
Thanks for asking. Will look into this

**Comment by Alchemist0823** [comment]
I removed emitEnded check before spawn method

**Comment by Alchemist0823** [comment]
Fixed in commit 89eee1879a0aa405c401de53e0959b90e4aa695d
