### ISSUE TITLE
Importing particle systems with color gradients are broken

### ISSUE THREAD

**Issue by pigloo** [Alchemist0823/three.quarks#42]
When using the editor to create particle effects, if you use the: behaviours > ColorOverLife > gradient feature and then export it subsequently fails to import properly in my tests, the gradients dont show up.

![Screenshot from 2023-01-04 19-51-36](https://user-images.githubusercontent.com/1707563/210637776-4fb1fa3d-6080-4153-ad53-b882b5bd14e1.png)

**Comment by Alchemist0823** [comment]
Thanks for pointing out. was fixed in 8bb8480f147c3129d8ae10b498e4d35f0b2632f0

**Comment by pigloo** [comment]
Thanks!

Might be an idea to update the editor hosted on your site too https://forrestsun.com/three.quarks-editor/

**Comment by Alchemist0823** [comment]
Yes, just did. you probably need to ctrl + f5 to refresh to get the latest version
