### ISSUE TITLE
Json import and world space scale not working

### ISSUE THREAD

**Issue by theripper93** [Alchemist0823/three.quarks#48]
Importing a json that has world space effects, then applying a scale to the container of the particle systems does not reflect on the object. This can also be verified in the visual editor by changing the scale of the “plasma projectile” example and observing it does nothing

**Comment by Alchemist0823** [comment]
Thanks for pointing out. it's fixed by #[af46ca6](https://github.com/Alchemist0823/three.quarks/commit/af46ca6d72b5e302ac8ecb57a3465f5cc8d6a0f9)
