### ISSUE TITLE
Changelog out of date and no release tags

### ISSUE THREAD

**Issue by marwie** [Alchemist0823/three.quarks#50]
Hello,

do you think you could update the changelog and push release tags to github? It would help with knowing when to update to which version / when new features are available 😊

Last release: 13 days ago, version 0.10.0
Changelog: almost a year ago, version 0.7.0

**Comment by Alchemist0823** [comment]
Thank you for your feedback. Yeah, we need better documentation.

**Comment by marwie** [comment]
I can relate 😉
