### ISSUE TITLE
Trails not working in r152

### ISSUE THREAD

**Issue by theripper93** [Alchemist0823/three.quarks#56]
Trails are not working in the latest threejs release

**Comment by hybridherbst** [comment]
Looks like the UV change affects the shaders here.
![image](https://github.com/Alchemist0823/three.quarks/assets/2693840/78890f5f-7108-4f84-a98f-787489596a0c)

E.g. these need to be probably changed:
https://github.com/Alchemist0823/three.quarks/blob/654972c7b83740b4add9f1b1a7c504658bd98ddb/src/shaders/particle_frag.glsl.ts#LL20C44-L20C44

**Comment by hybridherbst** [comment]
@Alchemist0823 are you interested in a PR?

**Comment by Alchemist0823** [comment]
Thanks for pointing out. Yeah, I am open for RP.

**Comment by Alchemist0823** [comment]
Fix in #0a4c2ef16c18db7f337e471c5c339b047577b764
