### ISSUE TITLE
Tone down the custom styling in the three.quarks log

### ISSUE THREAD

**Issue by hybridherbst** [Alchemist0823/three.quarks#63]
This is a bit ugly right now:
![image](https://github.com/Alchemist0823/three.quarks/assets/2693840/2649d4ba-9e5e-4016-95f2-e8188bfa0e30)

I think it's fine that there's a log, but could you maybe remove the styling from the log? Right now it looks like an error.

**Comment by Alchemist0823** [comment]
Sure thing

**Comment by Alchemist0823** [comment]
fixed in 1cace7bea856beef72d5715da3b19fb108505953
