### ISSUE TITLE
Horizontal- & Vertical billboards

### ISSUE THREAD

**Issue by marwie** [Alchemist0823/three.quarks#69]
Hello,

prior to 0.10.6 (in version 0.7.3) we could create horizontal and vertical billboarding by modifying the mesh geometry. This doesn't work anymore. Is there a way to add this behaviour again?

Old code:
```js
if (renderMode === ParticleSystemRenderMode.HorizontalBillboard) {
            geo = new THREE.BoxGeometry(1, 1, 0);
        }
        else if (renderMode === ParticleSystemRenderMode.VerticalBillboard) {
            geo = new THREE.BoxGeometry(1, 0, 1);
        }
```

**Comment by Alchemist0823** [comment]
Hi @marwie,
I will look into this.

**Comment by Alchemist0823** [comment]
@marwie , I think it's probably on your own private branch. I went back to 0.7.3. and didn't find Vertical and Horizontal Billboard.
right now you can do:
```
            instancingGeometry: new PlaneGeometry(1, 1).rotateX((-90 / 180) * Math.PI),
            renderMode: RenderMode.Mesh,
```
to support horizontal Billboard. vertical one that always face camera. i don't think we support that. we will it to our future feature list.

**Comment by marwie** [comment]
We dont have a private branch or fork. The code above is in needle engine and worked in quarks 0.7.3 as mentioned above to make particles behave correctly. 

I will try what you suggest soon, thank you. And adding this feature would be great :)

**Comment by marwie** [comment]
Works like a charm, thank you
