### ISSUE TITLE
Adjust log messaging

### ISSUE THREAD

**Issue by hybridherbst** [Alchemist0823/three.quarks#70]
Follow-up to #63 

We've had a few people voice confusion as to why their entire website is "powered by three.quarks" according to the logs.
Would it be possible to adjust the messaging to read "Particle Systems powered by three.quarks" or similar?

Thank you!

**Comment by Alchemist0823** [comment]
Yeah, make sense

**Comment by Alchemist0823** [comment]
25d5cb1d8ade220257f0553beeee246d689351c6

**Comment by marwie** [comment]
@Alchemist0823 do you think it would be possible to only show the console message once when particle are actually used - e.g. right now the message shows up immediately regardless if ever used or not
