### ISSUE TITLE
looping property in particle system configuration doesn't work (?)

### ISSUE THREAD

**Issue by Trusiak** [Alchemist0823/three.quarks#72]
hello, 

does looping property in particle system configuration work well?
In example muzzleFlashDemo animation, effect is constantly looping on the demo, even though each instance of the System has looping on false.

*but if we read effect from .json file, then looping work well

also you should remove      ` console.log(this.subEmissions.length, this.subParticleSystem.system.particleNum);`

**Comment by Alchemist0823** [comment]
The looping does work as expected. in the demo setup, demo.js file restart the set of particle system after certain period.
Yeah, thanks for feedback. we should have a lint rule to remove debug code.
