### ISSUE TITLE
Particle opacity behavior

### ISSUE THREAD

**Issue by ManHunter** [Alchemist0823/three.quarks#76]
I could not find a way to control the opacity of particles by analogy with **ColorOverLife**.
Are you planning to add this functionality?

**Comment by Alchemist0823** [comment]
Hey @ManHunter, In ColorOverLife, the color is a Vector4 the XYZ are for RGB, the w is for alpha (opacity)

**Comment by Alchemist0823** [comment]
export interface FunctionColorGenerator {
    type: 'function';
    genColor(color: Vector4, t: number): Vector4;
    toJSON(): FunctionJSON;
    clone(): FunctionColorGenerator;
}
