### ISSUE TITLE
how to start particle more than 1 time without looping 

### ISSUE THREAD

**Issue by Trusiak** [Alchemist0823/three.quarks#78]
I would like to create an effect such as we currently have on the three.quark website - i.e. pressing a button triggers an effect, the next press triggers another, etc. 

![image](https://github.com/Alchemist0823/three.quarks/assets/26073497/51cd6bba-c794-4784-a9cc-138b9df07b90)

Currently, using addSystem will simply add an effect to me that executes once (if it is not looped)

`this.quarksRenderer.addSystem(child.system);`

but calling the function again and creating a new object will not trigger the effect a second time - only loading it and downloading the asset again will allow this. 

So, how do you trigger effect after effect depending on the will of the user? (effect read from json file)

**Comment by Alchemist0823** [comment]
You could use the restart function on that system or traverse the object and call restart on every particle system in the object tree.

**Comment by Trusiak** [comment]
@Alchemist0823 i tried, but for some reason when system finished his work, it clears the children array - so i can't iterate throught and restart.

**Comment by Alchemist0823** [comment]
Can you attach your JSON file? 
also, could you search `autoDestroy` in the JSON file and set it to false?

**Comment by Trusiak** [comment]
ok, that helped. Thanks!
