### ISSUE TITLE
How are we supposed to create new effects?

### ISSUE THREAD

**Issue by hichemfantar** [Alchemist0823/three.quarks#88]
I'm new to particle systems but looking at the documentation, how are we supposed to generate the json files?

**Comment by Alchemist0823** [comment]
If you use the open source library only. you can use `toJson `on any parent object of ParticleEmitters to export JSON.

You can also use online cloud editor: https://quarks.art/create
Tutorial: https://www.youtube.com/watch?v=wenZ_B6MZRM&t=86s&ab_channel=QuarksVFX
