### ISSUE TITLE
How to properly cleanup in React

### ISSUE THREAD

**Issue by hichemfantar** [Alchemist0823/three.quarks#91]
This example shows how to use this library with react but it doesn't show to cleanup which causes a memory leak on rerender.

https://codesandbox.io/p/sandbox/three-quarks-with-react-three-fiber-llhvxk?file=%2Fsrc%2Findex.js%3A22%2C21

**Comment by hichemfantar** [comment]
I made an attempt but i'd like some feedback. It works but i'd like some different opinions on efficiency.
https://codesandbox.io/p/sandbox/three-quarks-with-react-three-fiber-forked-yyld3t?file=%2Fsrc%2Findex.js%3A35%2C33

**Comment by Alchemist0823** [comment]
Thanks for providing an example. I will consider updating our example, 
```
          batchRenderer.deleteSystem(element.system)
```
This line is not necessary. As long as the particle emitter is removed from the scene, the batchedRender will automatically remove it from system lists.
