### ISSUE TITLE
importing IParticleSystem interface causes build error

### ISSUE THREAD

**Issue by hichemfantar** [Alchemist0823/three.quarks#92]
**Describe the bug**

using `"vite": "^4.5.3"`:

`import { IParticleSystem } from "three.quarks";`

`Uncaught SyntaxError: The requested module '/@fs/Users/user/proj/node_modules/.vite/deps/three__quarks.js?v=4479a824' does not provide an export named 'IParticleSystem'
`

**To Reproduce**
1. import the interface `import { IParticleSystem } from "three.quarks";`
2. See error

**Expected behavior**
no error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**

**Comment by Alchemist0823** [comment]
HI @hichemfantar, I just created a vite project with typescript and three with `create-vite`
it doesn't reproduce the error you have.
If you used javascript only, it will generate errors because IParticleSystem is an interface not a class.

**Comment by hichemfantar** [comment]
@Alchemist0823 the issue happens when i import the interface via ES6 Destructuring.

this causes the error: `import { IParticleSystem } from "three.quarks";`

this doesn't: ```
import * as q from "three.quarks";
let particleEmittersAddedToScene: q.IParticleSystem[] = [];
```

**Comment by Alchemist0823** [comment]
![image](https://github.com/user-attachments/assets/7598b711-1af7-41c9-a06e-af9a7f49e8d1)
![image](https://github.com/user-attachments/assets/3dc61392-4ff2-4b7b-969a-26e18b0604ef)

**Comment by hichemfantar** [comment]
> ![image](https://private-user-images.githubusercontent.com/4423239/370831930-7598b711-1af7-41c9-a06e-af9a7f49e8d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTQ2NTQsIm5iZiI6MTcyNzI5NDM1NCwicGF0aCI6Ii80NDIzMjM5LzM3MDgzMTkzMC03NTk4YjcxMS0xYWY3LTQxYzktYTA2ZS1hZjlhN2Y0OWU4ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTk1OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDliMDc4ODk4ZjY2ODA3YjZhZTExNjYwODg5NGE1NTUwZmRkMTc5MzBiNGNlMzc0MDMxOWI5MDc5NjYzNmQxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sJp5NyQas1RSCbSUO4F3HKIqA7MX2KIZk6IUzTcH-sA) ![image](https://private-user-images.githubusercontent.com/4423239/370832026-3dc61392-4ff2-4b7b-969a-26e18b0604ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTQ2NTQsIm5iZiI6MTcyNzI5NDM1NCwicGF0aCI6Ii80NDIzMjM5LzM3MDgzMjAyNi0zZGM2MTM5Mi00ZmYyLTRiN2ItOTY5YS0yNmUxOGIwNjA0ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTk1OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI5ZGM0ZWU2NzBmZmRiY2I1NWMwY2RmMzYzZTFjZTkyNmZjNGY1YWUxOWU1ZjBhMTU4NjI1MWViZWI2NDBkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hGCiDxHNC16LkqxCe86YRY1XIymur0_qvT5X_LSxV5k)

aren't you using typescript?

**Comment by Alchemist0823** [comment]
I tried vite-create with typescript. It worked without any errors.

**Comment by hichemfantar** [comment]
turns out the issue was with the tsconfig
i removed `verbatimModuleSyntax": true,` and the problem was solved

thanks for the help!
