### ISSUE TITLE
does the QuarksLoader load method support caching?

### ISSUE THREAD

**Issue by hichemfantar** [Alchemist0823/three.quarks#94]
from my testing, i checked the network tab and it doesn't seem to cache the json response.
is there a way to configure this?

```
	useEffect(() => {
		const loader = new QuarksLoader();
		const interval = setInterval(() => {
			loader.load("/effect.json");
		}, 1000);
		return () => {
			clearInterval(interval);
		};
	}, []);
```

**Comment by Alchemist0823** [comment]
Thanks for asking. I will take a look QuarksLoader is inherited from ObjectLoader. as long as three.js's ObjectLoader support caching, the QuarksLoader should support.

**Comment by hichemfantar** [comment]
i believe this was just me forgetting to re enable caching in chrome dev tools, i don't think this is an issue
