### ISSUE TITLE
How to stop an effect from auto playing when added to the scene

### ISSUE THREAD

**Issue by hichemfantar** [Alchemist0823/three.quarks#96]
this code auto plays the effect as soon as it's added to the scene.
i added QuarksUtil.stop which seems to fix it but is this the recommended way?
wouldn't it make more sense that it doesn't play by default?

```
				QuarksUtil.addToBatchRenderer(obj, batchRenderer);
				QuarksUtil.stop(obj);
				scene.add(obj);

```

**Comment by Alchemist0823** [comment]
Thanks for asking. stop() or pause() the effect will fix the issue. because if we add a new api and make it stop by default. it's going to be an extra step for people who already uses the library to play the effect. it will introduce compatibility issue. that's the correct to fix your problem

**Comment by hichemfantar** [comment]
i believe i had weird behavior when calling pause() or stop(), i don't remember exactly but i believe the correct behavior should be not to play by default and only play when explicitly requested with play()
I believe this change warrants a major version bump which won't break existing projects.

**Comment by hichemfantar** [comment]
it seems the library is already at 0.x so breaking changes are to be expected.

you can either bump to 0.16 and add console.warn("effects no longer auto play on >=0.16") or bump the library to 1.0.0 to make sure existing projects don't break.
